package com.mycompany.scrollimage;

import java.awt.event.AdjustmentEvent;
import java.awt.event.AdjustmentListener;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.ScrollPaneConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.opencv.core.Core;

public class Interfaz extends javax.swing.JFrame {
    
    private JScrollBar barraVer;
    private JScrollBar barraHor;
    private EstadisticasImagen estRGB = new EstadisticasImagen();
    private JFileChooser fc = new JFileChooser();
    private JOptionPane dialog = new JOptionPane();
    private FileNameExtensionFilter filter = null;
    
    class MiListener implements AdjustmentListener {
        @Override
        public void adjustmentValueChanged(AdjustmentEvent e) {
            if (lienzo.getImage() != null){
                estRGB.calculaEstadisticas(lienzo.getImage(), panelDeslizable.getViewport().getViewPosition(), panelDeslizable.getViewport().getExtentSize());
                setRGB();
            }
        }
    }
    public Interfaz() {
        nu.pattern.OpenCV.loadShared();
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        barraVer = panelDeslizable.getVerticalScrollBar();
        barraHor = panelDeslizable.getHorizontalScrollBar();
        barraVer.addAdjustmentListener(new MiListener());
        barraHor.addAdjustmentListener(new MiListener());
        panelDeslizable.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        panelDeslizable.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDeslizable = new javax.swing.JScrollPane();
        lienzo = new com.mycompany.scrollimage.Lienzo();
        panelRGB = new javax.swing.JPanel();
        panelRed = new javax.swing.JPanel();
        labelRed = new javax.swing.JLabel();
        labelMinRed = new javax.swing.JLabel();
        labelMaxRed = new javax.swing.JLabel();
        labelPromRed = new javax.swing.JLabel();
        textMinRed = new javax.swing.JTextField();
        textMaxRed = new javax.swing.JTextField();
        textPromRed = new javax.swing.JTextField();
        panelGreen = new javax.swing.JPanel();
        labelGreen = new javax.swing.JLabel();
        labelMinGreen = new javax.swing.JLabel();
        labelMaxGreen = new javax.swing.JLabel();
        labelPromGreen = new javax.swing.JLabel();
        textMinGreen = new javax.swing.JTextField();
        textMaxGreen = new javax.swing.JTextField();
        textPromGreen = new javax.swing.JTextField();
        panelBlue = new javax.swing.JPanel();
        labelBlue = new javax.swing.JLabel();
        labelMinBlue = new javax.swing.JLabel();
        labelMaxBlue = new javax.swing.JLabel();
        labelPromBlue = new javax.swing.JLabel();
        textMinBlue = new javax.swing.JTextField();
        textMaxBlue = new javax.swing.JTextField();
        textPromBlue = new javax.swing.JTextField();
        labelCopyFer = new javax.swing.JLabel();
        labelCopyEdu = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmenuFile = new javax.swing.JMenu();
        abrirMenuItem = new javax.swing.JMenuItem();
        jmenuAbout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        panelDeslizable.setViewportView(lienzo);

        panelRGB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelRed.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelRed.setText("Red");

        labelMinRed.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelMinRed.setText("Valor mínimo");

        labelMaxRed.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelMaxRed.setText("Valor máximo");

        labelPromRed.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPromRed.setText("Valor promedio");

        textMinRed.setEditable(false);

        textMaxRed.setEditable(false);

        textPromRed.setEditable(false);

        javax.swing.GroupLayout panelRedLayout = new javax.swing.GroupLayout(panelRed);
        panelRed.setLayout(panelRedLayout);
        panelRedLayout.setHorizontalGroup(
            panelRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedLayout.createSequentialGroup()
                .addGroup(panelRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRedLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelPromRed, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelMaxRed, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelMinRed, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textMinRed, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textMaxRed, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textPromRed, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelRedLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(labelRed, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelRedLayout.setVerticalGroup(
            panelRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedLayout.createSequentialGroup()
                .addComponent(labelRed, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMinRed)
                    .addComponent(textMinRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(panelRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMaxRed)
                    .addComponent(textMaxRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPromRed)
                    .addComponent(textPromRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        labelGreen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelGreen.setText("Green");

        labelMinGreen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelMinGreen.setText("Valor mínimo");

        labelMaxGreen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelMaxGreen.setText("Valor máximo");

        labelPromGreen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPromGreen.setText("Valor promedio");

        textMinGreen.setEditable(false);

        textMaxGreen.setEditable(false);

        textPromGreen.setEditable(false);

        javax.swing.GroupLayout panelGreenLayout = new javax.swing.GroupLayout(panelGreen);
        panelGreen.setLayout(panelGreenLayout);
        panelGreenLayout.setHorizontalGroup(
            panelGreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGreenLayout.createSequentialGroup()
                .addGroup(panelGreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGreenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelGreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelPromGreen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelMaxGreen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelMinGreen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelGreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textMinGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textMaxGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textPromGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelGreenLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(labelGreen)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelGreenLayout.setVerticalGroup(
            panelGreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGreenLayout.createSequentialGroup()
                .addComponent(labelGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelGreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMinGreen)
                    .addComponent(textMinGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(panelGreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMaxGreen)
                    .addComponent(textMaxGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPromGreen)
                    .addComponent(textPromGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        labelBlue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelBlue.setText("Blue");

        labelMinBlue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelMinBlue.setText("Valor mínimo");

        labelMaxBlue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelMaxBlue.setText("Valor máximo");

        labelPromBlue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPromBlue.setText("Valor promedio");

        textMinBlue.setEditable(false);

        textMaxBlue.setEditable(false);

        textPromBlue.setEditable(false);

        javax.swing.GroupLayout panelBlueLayout = new javax.swing.GroupLayout(panelBlue);
        panelBlue.setLayout(panelBlueLayout);
        panelBlueLayout.setHorizontalGroup(
            panelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBlueLayout.createSequentialGroup()
                .addGroup(panelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBlueLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelPromBlue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelMaxBlue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelMinBlue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textMinBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textMaxBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textPromBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelBlueLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(labelBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelBlueLayout.setVerticalGroup(
            panelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBlueLayout.createSequentialGroup()
                .addComponent(labelBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMinBlue)
                    .addComponent(textMinBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(panelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMaxBlue)
                    .addComponent(textMaxBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPromBlue)
                    .addComponent(textPromBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelRGBLayout = new javax.swing.GroupLayout(panelRGB);
        panelRGB.setLayout(panelRGBLayout);
        panelRGBLayout.setHorizontalGroup(
            panelRGBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRGBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(panelBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelRGBLayout.setVerticalGroup(
            panelRGBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRGBLayout.createSequentialGroup()
                .addGroup(panelRGBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelGreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBlue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        labelCopyFer.setText("© Fernando Marcelo Alonso");

        labelCopyEdu.setText("    Eduardo Maldonado Fernández");

        jmenuFile.setText("File");

        abrirMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        abrirMenuItem.setText("Open Image");
        abrirMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirMenuItemActionPerformed(evt);
            }
        });
        jmenuFile.add(abrirMenuItem);

        jMenuBar1.add(jmenuFile);

        jmenuAbout.setText("About");
        jMenuBar1.add(jmenuAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panelRGB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelDeslizable))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(451, 451, 451)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCopyFer, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCopyEdu, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(panelDeslizable, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelRGB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(labelCopyFer, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCopyEdu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirMenuItemActionPerformed
        initFiltros();
        if(fc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION){
            lienzo.updateImage(fc.getSelectedFile()); 
            estRGB.calculaEstadisticas(lienzo.getImage(), panelDeslizable.getViewport().getViewPosition(), panelDeslizable.getViewport().getExtentSize());
            setRGB();
            panelDeslizable.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
            panelDeslizable.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        }
    }//GEN-LAST:event_abrirMenuItemActionPerformed
    
    public void initFiltros(){
        filter = new FileNameExtensionFilter("Images (*.jpg,*.png)","jpg", "png");
        fc.addChoosableFileFilter(filter);
        fc.setAcceptAllFileFilterUsed(false);
    }
    
    public void setRGB(){
        int [] max = estRGB.getMaximo();
        int [] min = estRGB.getMinimo();
        int [] prom = estRGB.getPromedio();
        textMaxBlue.setText(String.valueOf(max[0]));
        textMinBlue.setText(String.valueOf(min[0]));
        textPromBlue.setText(String.valueOf(prom[0]));
        textMaxGreen.setText(String.valueOf(max[1]));
        textMinGreen.setText(String.valueOf(min[1]));
        textPromGreen.setText(String.valueOf(prom[1]));
        textMaxRed.setText(String.valueOf(max[2]));
        textMinRed.setText(String.valueOf(min[2]));
        textPromRed.setText(String.valueOf(prom[2]));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrirMenuItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmenuAbout;
    private javax.swing.JMenu jmenuFile;
    private javax.swing.JLabel labelBlue;
    private javax.swing.JLabel labelCopyEdu;
    private javax.swing.JLabel labelCopyFer;
    private javax.swing.JLabel labelGreen;
    private javax.swing.JLabel labelMaxBlue;
    private javax.swing.JLabel labelMaxGreen;
    private javax.swing.JLabel labelMaxRed;
    private javax.swing.JLabel labelMinBlue;
    private javax.swing.JLabel labelMinGreen;
    private javax.swing.JLabel labelMinRed;
    private javax.swing.JLabel labelPromBlue;
    private javax.swing.JLabel labelPromGreen;
    private javax.swing.JLabel labelPromRed;
    private javax.swing.JLabel labelRed;
    private com.mycompany.scrollimage.Lienzo lienzo;
    private javax.swing.JPanel panelBlue;
    private javax.swing.JScrollPane panelDeslizable;
    private javax.swing.JPanel panelGreen;
    private javax.swing.JPanel panelRGB;
    private javax.swing.JPanel panelRed;
    private javax.swing.JTextField textMaxBlue;
    private javax.swing.JTextField textMaxGreen;
    private javax.swing.JTextField textMaxRed;
    private javax.swing.JTextField textMinBlue;
    private javax.swing.JTextField textMinGreen;
    private javax.swing.JTextField textMinRed;
    private javax.swing.JTextField textPromBlue;
    private javax.swing.JTextField textPromGreen;
    private javax.swing.JTextField textPromRed;
    // End of variables declaration//GEN-END:variables
}
